### ISSUE TITLE
Is there any consideration to using human readable time in DEVLOG?

### ISSUE THREAD

**Issue by kumajaya** [eclipse-4diac/4diac-forte#99]

**Comment by azoitl** [comment]
So far not. But I like the idea.

**Comment by kumajaya** [comment]
> So far not. But I like the idea.

Sir, something like https://github.com/eclipse-4diac/4diac-forte/pull/100 ?

**Comment by ernstblechaPT** [comment]
My 2 cents:
 - dropping the resolution down to milliseconds might be problematic since errors are now logged on the error-output-stream and all other messages are on the standard-output, this might lead to confusion due to the streams being out of order
 - it would probably be the most consistent option if the time format was the DATETIME format specified in IEC 61131-3
 - alternativly https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations could be utilized as it is easily parseable, but this would require the target device to have access to up-to-date timezone information

**Comment by azoitl** [comment]
Yesterday, when I first read the issue, I had as first idea to use NOW and the `toString()` Method to get the `Date_And_Time`'s IEC 61131-3 literal as representation. I only was not sure about the performance implications.

But before we continue here we need to get the Zephyr code out of this file. Otherwise the code is unreadable.

**Comment by kumajaya** [comment]
For the meanwhile, I convert the PR as a draft.

**Comment by kumajaya** [comment]
> Yesterday, when I first read the issue, I had as first idea to use NOW and the `toString()` Method to get the `Date_And_Time`'s IEC 61131-3 literal as representation. I only was not sure about the performance implications.
> 
> But before we continue here we need to get the Zephyr code out of this file. Otherwise the code is unreadable.

No issue for Windows, Linux, or embedded Linux but not sure about resource constrained device. For Zephyr, it does not use the standard chrono time functions.

**Comment by kumajaya** [comment]
Add switch, optional logger time in IEC 61131-3 date time literal.

**Comment by kumajaya** [comment]
PR https://github.com/eclipse-4diac/4diac-forte/pull/100 has been merged. Thank you all for the great guidance.
